spring:
  profiles:
    active: development
---
server:
  port: 8088
  tomcat.uri-encoding: UTF-8

spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3306/skillij?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 1q2w3e4r5t
    initialize: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    serialization: true
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

jwt:
  header: Authorization

logging:
  level:
    com.ystc.cloud: debug
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE