spring:
  profiles:
    active: development

server:
  port: 8080
  tomcat.uri-encoding: UTF-8

logging:
  level: debug

---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3306/skillij?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root2017
    initialize: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql
  data:
    mongodb:
      uri: mongodb://localhost:27017/skillij?maxPoolSize=256
  redis:
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    timeout: 0



---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://139.199.121.254:3306/skillij?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root2017
    initialize: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: mysql
  data:
    mongodb:
      uri: mongodb://139.199.121.254:27017/skillij?maxPoolSize=256